"""initial schema

Revision ID: 94c5b1e5439b
Revises: 
Create Date: 2026-06-25 23:30:26.414235
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94c5b1e5439b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('youtube_id', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('license_tag', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=8), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('package_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_theme'), ['theme'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('sentences',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('lesson_id', sa.String(length=64), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_zh', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_sentences_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentences')),
    sa.UniqueConstraint('lesson_id', 'idx', name=op.f('uq_sentences_lesson_id'))
    )
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentences_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sentence_id', sa.String(length=80), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('surface', sa.String(length=128), nullable=False),
    sa.Column('lemma', sa.String(length=64), nullable=False),
    sa.Column('pos', sa.String(length=16), nullable=True),
    sa.Column('dict_ref', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('fk_tokens_sentence_id_sentences'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens'))
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_lemma'), ['lemma'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_sentence_id'), ['sentence_id'], unique=False)

    op.create_table('vocab_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('lemma', sa.String(length=64), nullable=False),
    sa.Column('surface', sa.String(length=128), nullable=True),
    sa.Column('source_sentence_id', sa.String(length=80), nullable=True),
    sa.Column('mastery', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_sentence_id'], ['sentences.id'], name=op.f('fk_vocab_items_source_sentence_id_sentences'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vocab_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocab_items')),
    sa.UniqueConstraint('user_id', 'lemma', name=op.f('uq_vocab_items_user_id'))
    )
    with op.batch_alter_table('vocab_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocab_items_user_id'), ['user_id'], unique=False)

    op.create_table('word_index',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('lemma', sa.String(length=64), nullable=False),
    sa.Column('sentence_id', sa.String(length=80), nullable=False),
    sa.Column('lesson_id', sa.String(length=64), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_word_index_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('fk_word_index_sentence_id_sentences'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_word_index'))
    )
    with op.batch_alter_table('word_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_index_lemma'), ['lemma'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_index_lemma'))

    op.drop_table('word_index')
    with op.batch_alter_table('vocab_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocab_items_user_id'))

    op.drop_table('vocab_items')
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_sentence_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_lemma'))

    op.drop_table('tokens')
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentences_lesson_id'))

    op.drop_table('sentences')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_theme'))
        batch_op.drop_index(batch_op.f('ix_lessons_difficulty'))

    op.drop_table('lessons')
    # ### end Alembic commands ###
